"""Release readiness checklist generator.

Generates markdown checklists from readiness assessment results.
Items are actionable, trackable, and use Initiative 05 compatible format.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

from .readiness import ReadinessResult


@dataclass
class ChecklistItem:
    check_id: str
    name: str
    tier: str
    completed: bool = False
    action: str = ""


class ChecklistGenerator:
    def __init__(self, project_root: str | None = None):
        self.project_root = project_root

    def generate(self, result: ReadinessResult) -> list[ChecklistItem]:
        items: list[ChecklistItem] = []
        for check_result in result.checks:
            if not check_result.passed:
                items.append(ChecklistItem(
                    check_id=check_result.check.id,
                    name=check_result.check.name,
                    tier=check_result.check.tier,
                    completed=False,
                    action=check_result.check.remediation,
                ))
        return items

    def generate_markdown(self, result: ReadinessResult) -> str:
        items = self.generate(result)
        lines = [
            f"# Release Readiness Checklist",
            f"", f"_Generated: {datetime.utcnow().isoformat()}Z_",
            f"_Readiness score: **{result.readiness_score:.0%}**_",
            f"_Critical: {result.critical_passed}/{result.critical_count} passed_",
            f"", f"---", "",
        ]
        tiers = ["critical", "recommended", "optional"]
        tier_labels = {
            "critical": "Critical (must pass)",
            "recommended": "Recommended (should pass)",
            "optional": "Optional (nice to have)",
        }
        for tier in tiers:
            tier_items = [i for i in items if i.tier == tier]
            if not tier_items:
                continue
            lines.append(f"## {tier_labels[tier]}")
            lines.append("")
            for item in tier_items:
                status = "x" if item.completed else " "
                lines.append(f"- [{status}] **{item.name}** (`{item.check_id}`)")
                lines.append(f"  - {item.action}")
            lines.append("")

        if result.override_active:
            lines.append("---")
            lines.append("⚠️ **Override active**: Critical checks were bypassed.")
            lines.append("")

        lines.append("---")
        lines.append("_This checklist was auto-generated by SkillWeave release readiness assessment._")
        return "\n".join(lines)

    def save_markdown(self, result: ReadinessResult) -> str:
        markdown = self.generate_markdown(result)
        import os
        from pathlib import Path
        root = Path(self.project_root) if self.project_root else Path.cwd()
        checklists_dir = root / ".skillweave" / "checklists"
        os.makedirs(str(checklists_dir), exist_ok=True)
        filepath = checklists_dir / "release-readiness.md"
        filepath.write_text(markdown)
        return str(filepath)
