"""Auto-issue management module.

Generates issue templates, tracks issue state from commit patterns,
and produces structured issue reports for GitHub integration.
"""

import re
import json
from pathlib import Path
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


@dataclass
class IssueSuggestion:
    title: str
    body: str
    labels: list[str] = field(default_factory=list)
    source: str = ""


@dataclass
class ClosedByCommit:
    issue_ref: str
    sha: str
    message: str


@dataclass
class IssueManagerResult:
    timestamp: str = ""
    suggestions: list[IssueSuggestion] = field(default_factory=list)
    closed_issues: list[ClosedByCommit] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)


_ISSUE_REF_RE = re.compile(r"(?:close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved)\s+#(\d+)", re.IGNORECASE)
_TODO_RE = re.compile(r"(?:TODO|FIXME|HACK|XXX|BUG|WORKAROUND)\s*[:-]?\s*(.+)", re.IGNORECASE)


class IssueManager:
    def __init__(self, repo_root: str | None = None):
        self.repo_root = Path(repo_root) if repo_root else Path.cwd()

    def detect_closed_issues(self, messages: list[tuple[str, str]]) -> list[ClosedByCommit]:
        closed = []
        for sha, message in messages:
            matches = _ISSUE_REF_RE.findall(message)
            for ref in matches:
                closed.append(ClosedByCommit(
                    issue_ref=f"#{ref}",
                    sha=sha[:7],
                    message=message.split("\n")[0].strip(),
                ))
        return closed

    def scan_todos(self, file_content: str, file_path: str) -> list[IssueSuggestion]:
        suggestions = []
        for match in _TODO_RE.finditer(file_content):
            todo_text = match.group(1).strip()
            if len(todo_text) < 10:
                continue
            suggestions.append(IssueSuggestion(
                title=f"TODO: {todo_text[:80]}",
                body=f"Source: `{file_path}`\n\n```\n{todo_text}\n```",
                labels=["todo", "auto-detected"],
                source=file_path,
            ))
        return suggestions

    def generate_issue_body(self, suggestion: IssueSuggestion) -> str:
        lines = ["## Description", "", suggestion.body, ""]
        if suggestion.labels:
            lines.append("**Labels:** " + ", ".join(f"`{l}`" for l in suggestion.labels))
        lines.append("")
        lines.append("_Auto-generated by SkillWeave Issue Manager_")
        return "\n".join(lines)

    def analyze_commits(self, messages: list[tuple[str, str]]) -> IssueManagerResult:
        result = IssueManagerResult(
            timestamp=datetime.utcnow().isoformat() + "Z",
        )
        result.closed_issues = self.detect_closed_issues(messages)

        for sha, message in messages:
            line = message.split("\n")[0].strip()
            if line.startswith("feat") or line.startswith("feature"):
                desc = re.sub(r"^(feat|feature)(\([^)]*\))?!?:\s*", "", line, flags=re.IGNORECASE)
                result.suggestions.append(IssueSuggestion(
                    title=f"Track feature: {desc[:80]}",
                    body=f"Commit `{sha[:7]}` introduced:\n\n> {line}",
                    labels=["feature", "auto-detected"],
                    source=sha[:7],
                ))

        return result

    def generate_json(self, result: IssueManagerResult) -> str:
        return json.dumps({
            "timestamp": result.timestamp,
            "suggestions": [
                {"title": s.title, "labels": s.labels, "source": s.source}
                for s in result.suggestions
            ],
            "closed_issues": [
                {"issue_ref": c.issue_ref, "sha": c.sha, "message": c.message}
                for c in result.closed_issues
            ],
            "errors": result.errors,
        }, indent=2)
