FAIGATE_MAP = {
    "sonnet": "anthropic-sonnet",
    "claude-sonnet-4-5": "anthropic-sonnet",
    "haiku": "anthropic-haiku",
    "claude-haiku-3-5": "anthropic-haiku",
    "opus": "anthropic-claude",
    "claude-opus-4": "anthropic-claude",
    "gpt-4o": "openai-gpt4o",
    "gpt-4o-mini": "gemini-flash",
    "gemini-pro": "gemini-pro",
    "gemini-2-5-pro": "gemini-pro",
    "deepseek-v4": "deepseek-v4-pro",
    "deepseek-v4-pro": "deepseek-v4-pro",
    "llama-4": "openrouter-fallback",
    "llama-4-maverick": "openrouter-fallback",
    "mistral": "anthropic-claude",
    "mistral-large": "anthropic-claude",
}

OPENROUTER_MAP = {
    "sonnet": "anthropic/claude-3.5-sonnet",
    "claude-sonnet-4-5": "anthropic/claude-3.5-sonnet",
    "haiku": "anthropic/claude-3-haiku",
    "claude-haiku-3-5": "anthropic/claude-3-haiku",
    "opus": "anthropic/claude-3-opus",
    "claude-opus-4": "anthropic/claude-3-opus",
    "gpt-4o": "openai/gpt-4o",
    "gpt-4o-mini": "openai/gpt-4o-mini",
    "gemini-pro": "google/gemini-pro-1.5",
    "gemini-2-5-pro": "google/gemini-pro-1.5",
    "deepseek-v4": "deepseek/deepseek-coder",
    "deepseek-v4-pro": "deepseek/deepseek-coder",
    "llama-4": "meta-llama/llama-3-70b-instruct",
    "llama-4-maverick": "meta-llama/llama-3-70b-instruct",
    "mistral": "mistralai/mistral-large",
    "mistral-large": "mistralai/mistral-large",
}
