from .profile import (
    RoleDefinition,
    RoutingProfile,
    ToolSpec,
    from_dict,
    load_profile,
    load_profiles,
    load_matrix,
    builtin_roles,
    resolve_role,
    TIER_FAST,
    TIER_BALANCED,
    TIER_DEEP,
    CAP_MUTATE_RUN_STATE,
    CAP_APPROVE_GATE,
    INCOMPATIBLE_PAIRS,
    RoutingProfileError,
)

# The Faigate adapter is the shared model-routing surface. It lives here (not
# under council/) so both the council and the RunnerAdapter import the same
# module. The ``council.faigate_adapter`` path remains as a back-compat shim.
from .faigate_adapter import (  # noqa: F401
    CouncilProvider,
    FaigateProvider,
    ModelInfo,
    ROUTER_PROFILES,
    detect_providers,
    get_best_provider,
    get_profile,
    list_detected_providers,
    list_profiles,
)

__all__ = [
    "RoleDefinition",
    "RoutingProfile",
    "ToolSpec",
    "from_dict",
    "load_profile",
    "load_profiles",
    "load_matrix",
    "builtin_roles",
    "resolve_role",
    "TIER_FAST",
    "TIER_BALANCED",
    "TIER_DEEP",
    "CAP_MUTATE_RUN_STATE",
    "CAP_APPROVE_GATE",
    "INCOMPATIBLE_PAIRS",
    "RoutingProfileError",
    "CouncilProvider",
    "FaigateProvider",
    "ModelInfo",
    "ROUTER_PROFILES",
    "detect_providers",
    "get_best_provider",
    "get_profile",
    "list_detected_providers",
    "list_profiles",
]
