"""SkillWeave promptchain execution surface.

``execute`` is the executor for ``sequences/*.yaml`` orchestration files: it
loads a sequence, refuses one that does not declare ``session_boundary``, and
turns lanes marked ``parallel_lanes`` into subagent dispatches while leaving
``serialized_lanes`` inline.
"""

from .execute import (
    SequenceDeclaration,
    Lane,
    DispatchPlan,
    DispatchEntry,
    SUBAGENT,
    INLINE,
    MissingSessionBoundaryError,
    load_sequence,
    build_dispatch_plan,
    execute_sequence,
    BatchCommand,
    SessionState,
    SessionRun,
    Session,
    SessionConsumedError,
    SessionExecutionError,
    load_state_file,
    ProfileChainError,
    PreviewExecutionError,
    ChainStep,
    ProfileChainDerivation,
    profile_identity,
    preview_dimensions_of,
    require_supported_dimension,
    derive_chain_from_profile,
    build_dispatch_order,
    criterion_coverage,
    validate_profile_chain,
    dispatch_topology_from_profile,
)

__all__ = [
    "SequenceDeclaration",
    "Lane",
    "DispatchPlan",
    "DispatchEntry",
    "SUBAGENT",
    "INLINE",
    "MissingSessionBoundaryError",
    "load_sequence",
    "build_dispatch_plan",
    "execute_sequence",
    "BatchCommand",
    "SessionState",
    "SessionRun",
    "Session",
    "SessionConsumedError",
    "SessionExecutionError",
    "load_state_file",
    "ProfileChainError",
    "PreviewExecutionError",
    "ChainStep",
    "ProfileChainDerivation",
    "profile_identity",
    "preview_dimensions_of",
    "require_supported_dimension",
    "derive_chain_from_profile",
    "build_dispatch_order",
    "criterion_coverage",
    "validate_profile_chain",
    "dispatch_topology_from_profile",
]
