#!/usr/bin/env python3
"""regen-sequence — canonical SkillWeave dispatch-sequence tool.

The canonical producer of build-format ``execution-sequences.yaml`` from a PRD
and the tool that turns a lane-bearing sequence into one review brief per lane.
``promptchain-execute`` dispatches the emitted sequences; the emitted files
start with the header ``# generated by scripts/regen-sequence.py`` so the
validator pins the build format before checking it (see
``skills/skillweave-promptchain-validate``).

Commands:

    regen-sequence.py --from-prd <prd.json> [--out DIR]
    regen-sequence.py --generate-review-briefs <execution-sequences.yaml> [--out DIR]
    regen-sequence.py --inject-prd <prd_dir> [--repo DIR]

A build sequence is a ``phases`` block whose lanes are grouped under
``parallel_lanes`` (one subagent per lane, disjoint write surface) and
``serialized_lanes`` (shared surface, never concurrent), with
``session_boundary: batch``. Review briefs are written as
``review-brief-<lane_id>.md`` and carry the lane ID, the task IDs the lane
dispatches, the acceptance criteria read from the YAML, suggested verification
steps, and a VERDICT template — the reviewer is read-only, refetches every
branch tip, and never accepts a lane's own test run as evidence.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Mapping, Optional

import yaml

#: regen-sequence.py reads at most this many acceptance criteria per dispatch.
#: Mirrored by tests/contract/test_skill_asset_practice.py.
MAX_CRITERIA_PER_DISPATCH = 3

#: Keys the generator's ``_sequence`` and ``_briefs`` read unconditionally from
#: the ``sequence`` block; a missing key fails closed with zero dispatches.
SEQUENCE_REQUIRED_KEYS = (
    "sequence_id",
    "sequence_type",
    "execution_mode",
    "worktree",
    "branch",
    "base",
    "state_file",
    "runner_shell",
)

_GENERATOR_HEADER = "# generated by scripts/regen-sequence.py"


@dataclass
class LaneInfo:
    """One lane extracted from a build or operator dispatch sequence."""

    lane_id: str
    #: ``"parallel"``, ``"serialized"`` or ``"lane"`` (top-level lanes block).
    kind: str
    phase: str = ""
    task_ids: list[str] = field(default_factory=list)
    criteria: list[Any] = field(default_factory=list)
    verification: list[str] = field(default_factory=list)
    worktree: str = ""
    branch: str = ""
    write_scope: list[str] = field(default_factory=list)


def _first_list(raw: Mapping[str, Any], keys: tuple[str, ...]) -> list[Any]:
    for key in keys:
        value = raw.get(key)
        if value:
            return list(value)
    return []


def _write_surface(raw: Mapping[str, Any]) -> list[str]:
    surface: list[str] = []
    for key in ("creates", "modifies"):
        value = raw.get(key)
        if isinstance(value, str):
            surface.append(f"{key}: {value}")
        elif isinstance(value, list):
            surface.extend(f"{key}: {item}" for item in value if isinstance(item, str))
    return surface


def _lane_from_manifest(raw: Mapping[str, Any], kind: str, phase: str) -> LaneInfo:
    lane_id = raw.get("id") or raw.get("lane_id") or ""
    criteria: list[Any] = _first_list(
        raw, ("criteria", "acceptance_criteria", "gates")
    )
    if isinstance(raw.get("gates"), list):
        criteria.extend(g for g in raw["gates"] if isinstance(g, str))
    for group in raw.get("criterion_groups") or []:
        criteria.extend(f"criterion {c}" for c in (group.get("criteria") or []))
    write_scope = list(raw.get("write_scope") or []) or _write_surface(raw)
    return LaneInfo(
        lane_id=lane_id,
        kind=kind,
        phase=phase,
        task_ids=_first_list(raw, ("dispatches", "tasks", "task_ids", "steps")),
        criteria=criteria,
        verification=_first_list(
            raw, ("verification", "verification_steps", "checks")
        ),
        worktree=raw.get("worktree") or "",
        branch=raw.get("branch") or "",
        write_scope=write_scope,
    )


def extract_lanes(sequence: Mapping[str, Any]) -> list[LaneInfo]:
    """Collect every lane from a sequence declaration.

    Handles the operator dispatch format (top-level ``lanes``) and the build
    format (``parallel_lanes`` / ``serialized_lanes`` blocks inside ``phases``).
    """
    lanes: list[LaneInfo] = []
    for raw in sequence.get("lanes") or []:
        lanes.append(_lane_from_manifest(raw, kind="lane", phase=""))
    for phase in sequence.get("phases") or []:
        phase_name = (
            phase.get("name") or phase.get("id") or phase.get("phase") or ""
        )
        for raw in phase.get("parallel_lanes") or []:
            lanes.append(_lane_from_manifest(raw, kind="parallel", phase=phase_name))
        for raw in phase.get("serialized_lanes") or []:
            lanes.append(_lane_from_manifest(raw, kind="serialized", phase=phase_name))
    return lanes


def render_review_brief(lane: LaneInfo) -> str:
    """Render the review-brief template for one lane."""
    lines: list[str] = []
    lines.append(f"# Review Brief: {lane.lane_id}")
    lines.append("")
    lines.append(
        "Generated by `scripts/regen-sequence.py --generate-review-briefs`. "
        "One brief per lane. The reviewer holds a separate, read-only role: it "
        "refetches every branch tip and names the full SHA it judged, and never "
        "accepts the lane's own test run as evidence."
    )
    lines.append("")
    lines.append("## Lane")
    lines.append("")
    lines.append(f"- Lane ID: {lane.lane_id}")
    lines.append(f"- Kind: {lane.kind}")
    lines.append(f"- Phase: {lane.phase or '—'}")
    lines.append(f"- Worktree: {lane.worktree or '—'}")
    lines.append(f"- Branch: {lane.branch or '—'}")
    if lane.write_scope:
        lines.append("- Write scope:")
        lines.extend(f"  - {s}" for s in lane.write_scope)
    lines.append("")
    lines.append("## Task IDs")
    lines.append("")
    if lane.task_ids:
        lines.extend(f"- {tid}" for tid in lane.task_ids)
    else:
        lines.append("- (none declared)")
    lines.append("")
    lines.append("## Acceptance Criteria")
    lines.append("")
    if lane.criteria:
        lines.extend(f"- {c}" for c in lane.criteria)
    else:
        lines.append("- (none declared)")
    lines.append("")
    lines.append("## Suggested Verification Steps")
    lines.append("")
    verification = lane.verification or [
        "Run the lane's declared test target and record pass/fail with output.",
        "Re-run each red proof against the base; exit 1 must reproduce before any fix.",
        "Refetch the branch tip and name the full reviewed SHA in the verdict.",
        "Spot-check one claim independently rather than following the lane's own run.",
    ]
    for index, step in enumerate(verification, start=1):
        lines.append(f"{index}. {step}")
    lines.append("")
    lines.append("## VERDICT")
    lines.append("")
    lines.append("- VERDICT: PASS | FAIL | DEFER")
    lines.append("- Reviewed SHA: <full 40-hex SHA of the judged branch tip>")
    lines.append("- Evidence: <file:line or command output that produced the finding>")
    lines.append("- Findings:")
    lines.append("  - ")
    lines.append("- The reviewer repairs nothing and merges nothing.")
    lines.append("")
    return "\n".join(lines)


def generate_review_briefs(sequence_path: Path, out_dir: Path) -> list[Path]:
    """Write one ``review-brief-<lane_id>.md`` per lane; return written paths.

    Raises ``yaml.YAMLError`` for malformed input. A sequence with no lanes
    writes nothing and returns an empty list.
    """
    sequence = yaml.safe_load(sequence_path.read_text(encoding="utf-8"))
    if not isinstance(sequence, dict):
        raise ValueError(f"{sequence_path} is not a mapping document")
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for lane in extract_lanes(sequence):
        if not lane.lane_id:
            print(
                "regen-sequence: skipping lane without an id", file=sys.stderr
            )
            continue
        target = out_dir / f"review-brief-{lane.lane_id}.md"
        target.write_text(render_review_brief(lane), encoding="utf-8")
        written.append(target)
    return written


def inject_prd(prd_dir: Path, repo_root: Path) -> Path:
    """Inject the governing PRD artifacts into ``repo_root/.skillweave/``.

    ``prd.json`` holds the requirements a lane must honour (the task list, the
    acceptance criteria, the creates/modifies paths); ``prd.md`` is the narrative
    summary. Both are copied so an agent that reads ``.skillweave/`` sees the full
    intent, not only the summary. This is the same ``prd.json`` artifact that
    ``--from-prd`` consumes, so sequence generation and injection are keyed to one
    shape. Fails closed when ``prd_dir/prd.json`` is absent.
    """
    source_json = prd_dir / "prd.json"
    if not source_json.is_file():
        raise FileNotFoundError(f"no prd.json in PRD directory {prd_dir}")
    target_dir = repo_root / ".skillweave"
    target_dir.mkdir(parents=True, exist_ok=True)
    target = target_dir / "prd.json"
    shutil.copy2(source_json, target)
    narrative = prd_dir / "prd.md"
    if narrative.is_file():
        shutil.copy2(narrative, target_dir / "prd.md")
    return target


def _task_surface(task: Mapping[str, Any]) -> set[str]:
    lane = task.get("lane") or {}
    surface: set[str] = set()
    for key in ("creates", "modifies"):
        value = lane.get(key)
        if isinstance(value, str):
            surface.add(value)
        elif isinstance(value, list):
            surface.update(v for v in value if isinstance(v, str))
    return surface


def _declared_paths(task: Mapping[str, Any]) -> list[tuple[str, str]]:
    """The lane's declared ``creates``/``modifies`` paths as (kind, path) pairs.

    ``kind`` is the key that declared the path, so a path that a lane promises
    to create can be validated differently from one it claims to modify.
    """
    lane = task.get("lane") or {}
    pairs: list[tuple[str, str]] = []
    for key in ("creates", "modifies"):
        value = lane.get(key)
        if isinstance(value, str):
            pairs.append((key, value))
        elif isinstance(value, list):
            pairs.extend((key, v) for v in value if isinstance(v, str))
    return pairs


def resolve_lane_surfaces(
    task: Mapping[str, Any], repo_root: Path
) -> set[str]:
    """Resolve a lane's declared ``creates``/``modifies`` paths into real paths.

    Each declared surface must *resolve in the target repository* or this
    raises ``ValueError`` naming every unresolvable path — the generator fails
    closed before a single lane exists, never emitting a lane whose declared
    surfaces do not exist.

    Resolution rules, fail-closed like the rest of the generator:

    * a path declared under ``modifies`` must already exist in the repository
      as a file (a lane cannot modify a file that is not there) — an invented
      path like the 1.5.1 ``src/cli.py`` is refused, naming the path;
    * a path declared under ``creates`` resolves when its parent directory
      exists in the repository; the generator never invents the directory the
      file would be created under.

    ``repo_root`` is rooted against the repository top level; a declared path
    escaping it (``..``) is unresolvable. The returned set holds the
    repository-resolved, normalized path strings the phasing and mutual
    exclusion logic key on, so two lanes naming the same real file collide on
    the same key.
    """
    root = repo_root.resolve()
    unresolvable: list[tuple[str, str]] = []
    resolved: set[str] = set()
    for kind, raw in _declared_paths(task):
        # A path that would escape the repository root does not resolve in it.
        candidate = (root / raw).resolve()
        try:
            candidate.relative_to(root)
        except ValueError:
            unresolvable.append((kind, raw))
            continue
        if kind == "modifies":
            if not candidate.is_file():
                unresolvable.append((kind, raw))
            else:
                # Canonical, portable relative form: two lanes naming the same
                # real file (via ``./``, ``..`` or a different spelling) collapse
                # to one key, so exclusion and phasing see the collision.
                resolved.add(candidate.relative_to(root).as_posix())
        elif kind == "creates":
            # A create target resolves when its parent directory exists in the
            # repository; the generator never invents the directory it would be
            # created under. An already-existing target is not refused here — a
            # lane may ship a freshly scaffolded file — but a path under a
            # directory the repository does not have is unresolvable.
            if not candidate.parent.is_dir():
                unresolvable.append((kind, raw))
            else:
                resolved.add(candidate.relative_to(root).as_posix())
    if unresolvable:
        named = ", ".join(f"{kind}:{path}" for kind, path in unresolvable)
        raise ValueError(
            f"lane {task.get('id', '<no-id>')!r} declares unresolvable "
            f"surface(s) in repository {root}: {named}"
        )
    return resolved


def _topological_levels(tasks: list[Mapping[str, Any]]) -> dict[str, int]:
    by_id = {task["id"]: task for task in tasks}
    depth: dict[str, int] = {}

    def visit(task: Mapping[str, Any]) -> int:
        task_id = task["id"]
        if task_id in depth:
            return depth[task_id]
        deps = task.get("dependsOn") or task.get("dependencies") or []
        if not deps:
            depth[task_id] = 0
            return 0
        unresolved = [d for d in deps if d not in by_id]
        if unresolved:
            raise ValueError(
                f"task {task_id!r} depends on unknown task(s): {unresolved}"
            )
        depth[task_id] = 1 + max(visit(by_id[d]) for d in deps)
        return depth[task_id]

    for task in tasks:
        visit(task)
    return depth


def _lane_entry(task: Mapping[str, Any], sequence: Mapping[str, Any]) -> dict[str, Any]:
    lane = task.get("lane") or {}
    lane_id = lane.get("id") or f"lane-{task['id'].lower()}"
    entry: dict[str, Any] = {
        "id": lane_id,
        "criteria": list(task["acceptanceCriteria"]),
        "dispatches": [task["id"]],
        "points": task.get("points", 1),
    }
    for key in ("worktree", "branch"):
        if lane.get(key):
            entry[key] = lane[key]
        elif sequence.get(key):
            entry[key] = sequence[key]
    for key in ("creates", "modifies", "reads", "tests", "must_not_touch", "base"):
        if lane.get(key):
            entry[key] = lane[key]
    if lane.get("dispatch_order"):
        entry["dispatch_order"] = lane["dispatch_order"]
    return entry


def _surfaces_for(
    task: Mapping[str, Any],
    resolved: Optional[dict[str, set[str]]],
) -> set[str]:
    """The write surface used for phasing and exclusion decisions.

    When ``resolved`` (repository-resolved, canonical paths) is available it is
    authoritative — two lanes touching one real file collide even when they
    spell it differently. Otherwise the raw declared surface is used, preserving
    the generator's previous behaviour when no repository is known.
    """
    if resolved is not None:
        return resolved.get(task.get("id"), set())
    return _task_surface(task)


def _build_phases(
    tasks: list[Mapping[str, Any]],
    levels: dict[str, int],
    phase_names: Mapping[Any, Any],
    sequence: Mapping[str, Any],
    resolved: Optional[dict[str, set[str]]] = None,
) -> list[dict[str, Any]]:
    by_level: dict[int, list[Mapping[str, Any]]] = {}
    for task in tasks:
        by_level.setdefault(levels[task["id"]], []).append(task)

    phases: list[dict[str, Any]] = []
    for level in sorted(by_level):
        parallel: list[dict[str, Any]] = []
        serialized: list[dict[str, Any]] = []
        taken: set[str] = set()
        for task in by_level[level]:
            surface = _surfaces_for(task, resolved)
            if surface & taken:
                serialized.append(_lane_entry(task, sequence))
            else:
                parallel.append(_lane_entry(task, sequence))
                taken |= surface
        phase: dict[str, Any] = {
            "level": level,
            "name": phase_names.get(str(level), phase_names.get(level, f"phase-{level}")),
            "session": "separate",
            "dispatches_total": len(parallel) + len(serialized),
        }
        if parallel:
            phase["parallel_lanes"] = parallel
        if serialized:
            phase["serialized_lanes"] = serialized
        phases.append(phase)
    return phases


def _mutual_exclusion(
    tasks: list[Mapping[str, Any]],
    resolved: Optional[dict[str, set[str]]] = None,
) -> list[dict[str, Any]]:
    owners: dict[str, list[str]] = {}
    for task in tasks:
        for surface in _surfaces_for(task, resolved):
            owners.setdefault(surface, []).append(task["id"])
    return [
        {
            "surface": surface,
            "tasks": task_ids,
            "rule": "at_most_one_in_flight",
        }
        for surface, task_ids in owners.items()
        if len(task_ids) > 1
    ]


def _gate_pass_requires(phases: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return [
        {
            "level": phase["level"],
            "requires": [
                "branch tip refetched and full SHA named",
                "reviewer role separate from ops; reviewer does not repair or merge",
                "red proofs exit 1 against the base before any fix",
            ],
        }
        for phase in phases
    ]


def build_execution_sequences(
    prd: Mapping[str, Any],
    repo_root: Optional[Path] = None,
) -> dict[str, Any]:
    """Derive a build-format ``execution-sequences.yaml`` from a PRD.

    Fails closed exactly like the canonical generator: a missing ``sequence``
    block, a missing required sequence key, or a task without
    ``acceptanceCriteria`` raises before a single lane exists.

    When ``repo_root`` names the target repository, every lane's declared
    ``creates``/``modifies`` surfaces are additionally resolved against it
    (SW-BRIEF-001 / SW152): a surface that does not resolve raises, naming the
    path, before any lane is emitted. Resolution also feeds the phasing and
    ``mutual_exclusion`` decisions, so two lanes that touch the same real file
    collide even when they spell it differently. With ``repo_root`` omitted the
    surfaces are not filesystem-validated and raw declared paths are used, so
    callers that generate without a repository keep their previous behaviour.
    """
    sequence = prd.get("sequence")
    if not isinstance(sequence, dict):
        raise KeyError("PRD has no 'sequence' block")
    for key in SEQUENCE_REQUIRED_KEYS:
        if key not in sequence:
            raise KeyError(f"sequence block is missing required key {key!r}")
    tasks = prd.get("tasks")
    if not isinstance(tasks, list) or not tasks:
        raise ValueError("PRD has no tasks")
    for task in tasks:
        if "acceptanceCriteria" not in task:
            raise KeyError(f"task {task.get('id')!r} has no acceptanceCriteria")

    resolved: Optional[dict[str, set[str]]] = None
    if repo_root is not None:
        resolved = {
            task["id"]: resolve_lane_surfaces(task, repo_root) for task in tasks
        }

    levels = _topological_levels(tasks)
    phases = _build_phases(tasks, levels, sequence.get("phase_names") or {}, sequence, resolved)
    return {
        "sequence_id": sequence["sequence_id"],
        "sequence_type": sequence.get("sequence_type", "build"),
        "execution_mode": sequence.get("execution_mode", "ralph_attended"),
        "session_boundary": sequence.get("session_boundary", "batch"),
        "worktree": sequence["worktree"],
        "branch": sequence["branch"],
        "base": sequence["base"],
        "state_file": sequence["state_file"],
        "runner_shell": sequence["runner_shell"],
        "phases": phases,
        "mutual_exclusion": _mutual_exclusion(tasks, resolved),
        "gate_pass_requires": _gate_pass_requires(phases),
    }


def render_execution_sequences(sequence: Mapping[str, Any]) -> str:
    """Render a build sequence with the canonical generator header."""
    body = yaml.safe_dump(
        dict(sequence), sort_keys=False, allow_unicode=True, default_flow_style=False
    )
    return f"{_GENERATOR_HEADER}\n{body}"


def main(argv: Optional[list[str]] = None) -> int:
    ap = argparse.ArgumentParser(prog="regen-sequence", description=__doc__)
    ap.add_argument(
        "--from-prd", type=Path, metavar="prd.json",
        help="emit build-format execution-sequences.yaml from a PRD JSON",
    )
    ap.add_argument(
        "--generate-review-briefs", type=Path, metavar="execution-sequences.yaml",
        help="write one review-brief-<lane_id>.md per lane",
    )
    ap.add_argument(
        "--inject-prd", type=Path, metavar="prd_dir",
        help="copy prd.json (and prd.md if present) into .skillweave/ at the worktree root",
    )
    ap.add_argument(
        "--out", type=Path, default=Path("."),
        help="output directory (default: current directory)",
    )
    ap.add_argument(
        "--repo", type=Path, default=Path("."),
        help=(
            "target repository root: --from-prd resolves and validates every "
            "lane's creates/modifies surfaces against it, and --inject-prd "
            "copies prd.json into its .skillweave/ (default: current directory)"
        ),
    )
    args = ap.parse_args(argv)

    actions = sum(
        1 for flag in (args.from_prd, args.generate_review_briefs, args.inject_prd)
        if flag is not None
    )
    if actions != 1:
        ap.error(
            "exactly one of --from-prd, --generate-review-briefs, --inject-prd is required"
        )

    if args.generate_review_briefs is not None:
        written = generate_review_briefs(args.generate_review_briefs, args.out)
        if not written:
            print(
                "regen-sequence: no lanes found; wrote no review briefs",
                file=sys.stderr,
            )
            return 1
        for path in written:
            print(f"regen-sequence: wrote {path}")
        return 0

    if args.inject_prd is not None:
        target = inject_prd(args.inject_prd, args.repo)
        print(f"regen-sequence: injected {target}")
        return 0

    prd = json.loads(args.from_prd.read_text(encoding="utf-8"))
    sequence = build_execution_sequences(prd, repo_root=args.repo)
    target = args.out / "execution-sequences.yaml"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_execution_sequences(sequence), encoding="utf-8")
    print(f"regen-sequence: wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
