import os
import subprocess
import yaml
from typing import List, Optional

from .phase_detection import detect_phase_with_detail
from .workflow_recommendation import recommend


ONBOARDING_STATE_PATH = ".skillweave/onboarding-state.yaml"

# The substrate exclusion entry, kept in sync with the one that
# SkillWeavePersistence._ensure_gitignore writes (see docs/substrate-map.md,
# invariant 5). Anchored so a nested fixture root is not swallowed.
GITIGNORE_ENTRY = "/.skillweave/"

# The public mirror host. A repository whose ``origin`` remote resolves here is
# the read-only GitHub mirror of this tool and must never carry substrate
# content (docs/substrate-map.md, invariant 5).
PUBLIC_HOST = "github.com"

# The substrate rule, taught during onboarding. It is stated verbatim so a new
# project ends up configured correctly without the operator explaining it.
SUBSTRATE_RULE = (
    "The substrate rule: what lives under `.skillweave/` (PRDs, specs, "
    "sequences, discovery findings, handover records) is generated project "
    "intellectual property, not open content. Direction, durability and "
    "disclosure are declared per area, and git answers none of them on its "
    "own. A public repository never carries substrate content; it is tracked "
    "only in the private per-org planning repository. A dispatched lane "
    "receives its PRD by injection, so committing the substrate to make it "
    "reachable trades an IP boundary for a convenience the dispatcher already "
    "provides."
)


def _is_git_project(root: str) -> bool:
    """True when ``root`` lives inside a git work tree."""
    dotgit = os.path.join(root, ".git")
    # A worktree uses a ``.git`` *file*; a normal checkout uses a directory.
    if os.path.isdir(dotgit) or os.path.isfile(dotgit):
        return True
    return _git_top_level(root) is not None


def _git_top_level(root: str) -> Optional[str]:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            cwd=root,
            capture_output=True,
            text=True,
            timeout=5,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if out.returncode != 0:
        return None
    return out.stdout.strip() or None


def _git_origin_url(root: str) -> Optional[str]:
    try:
        out = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            cwd=root,
            capture_output=True,
            text=True,
            timeout=5,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if out.returncode != 0:
        return None
    return out.stdout.strip() or None


def _is_public_remote(url: Optional[str]) -> bool:
    """True when the ``origin`` remote points at a public host.

    The public GitHub mirror is the only host the product itself treats as
    public (this repository is mirrored read-only to ``github.com``). A local
    or self-hosted forge is not assumed public.
    """
    if not url:
        return False
    return PUBLIC_HOST in url


def _git_tracked_substrate(root: str) -> List[str]:
    """Paths under `.skillweave/` that git is currently tracking."""
    try:
        out = subprocess.run(
            ["git", "ls-files", "--cached", ".skillweave"],
            cwd=root,
            capture_output=True,
            text=True,
            timeout=5,
        )
    except (OSError, subprocess.TimeoutExpired):
        return []
    if out.returncode != 0:
        return []
    return [line for line in out.stdout.splitlines() if line.strip()]


def _ensure_gitignore_exclusion(root: str) -> bool:
    """Add the anchored substrate exclusion to ``.gitignore``, if absent.

    Returns True when the file was written. An absent ``.gitignore`` is
    created so that a git project can never silently leave the substrate
    tracked.
    """
    path = os.path.join(root, ".gitignore")
    content = ""
    if os.path.exists(path):
        with open(path) as f:
            content = f.read()
    lines = content.splitlines()
    if GITIGNORE_ENTRY in lines:
        return False
    lines.append("")
    lines.append("# SkillWeave substrate (auto-generated by onboarding)")
    lines.append(GITIGNORE_ENTRY)
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return True


def _ask_yes_no(prompt: str) -> bool:
    while True:
        answer = input(prompt).strip().lower()
        if answer in ("y", "yes"):
            return True
        if answer in ("n", "no"):
            return False


def _teach_substrate_rule(root: str, state: dict) -> Optional[dict]:
    """Teach the substrate rule and enforce the git side of it.

    Returns a refusal dict when the substrate must not be left tracked (a
    public repository whose substrate git is currently tracking), and
    mutates ``state`` with the recorded answers otherwise.
    """
    print("\n" + SUBSTRATE_RULE + "\n")

    if not _is_git_project(root):
        state["substrate"] = {"is_git_project": False}
        return None

    state["substrate"] = {"is_git_project": True}

    wrote = _ensure_gitignore_exclusion(root)
    state["substrate"]["gitignore_exclusion_written"] = wrote

    public = _is_public_remote(_git_origin_url(root))
    state["substrate"]["origin_is_public"] = public

    if public:
        tracked = _git_tracked_substrate(root)
        if tracked:
            return {
                "substrate_refused": True,
                "substrate_reason": (
                    "This repository's origin remote is public, but git is "
                    "already tracking substrate content under `.skillweave/`. "
                    "A public repository must never carry substrate content; "
                    "it belongs in the private per-org planning repository. "
                    "Untrack it with `git rm -r --cached .skillweave` and "
                    "re-run onboarding."
                ),
                "substrate_tracked": tracked,
            }

    return None


def run_onboarding(project_root: str = ".", skip: bool = False) -> dict:
    if skip:
        return {"skipped": True}

    root = os.path.abspath(project_root)

    detection = detect_phase_with_detail(root)
    detected_phase = detection["phase"]
    confidence = detection["confidence"]
    print(f"Detected phase: {detected_phase} (confidence: {confidence:.0%})")

    if confidence >= 0.5:
        print(f"Based on project artifacts, you appear to be in the **{detected_phase}** phase.")
    else:
        print("Could not automatically detect your project phase.")
        detected_phase = _ask_phase()

    goal = input("What is your goal? (e.g. 'build an app', 'ship it', 'research'): ").strip()
    if not goal:
        goal = None

    result = recommend(project_root=root, override_phase=detected_phase, goal=goal)

    print(f"\nRecommended bundle: **{result['bundle_name']}**")
    print(f"Next action: {result['next_action']}")
    if result["gap_analysis"].get("missing_phases"):
        print(f"Upcoming phases: {', '.join(result['gap_analysis']['missing_phases'])}")
    print(f"\n{result['message']}")

    state = {
        "phase": detected_phase,
        "goal": goal,
        "recommended_bundle": result["recommended_bundle"],
        "next_action": result["next_action"],
        "timestamp": __import__("datetime").datetime.now().isoformat(),
    }

    # The substrate rule is taught, not only enforced: state it, and for a git
    # project write the .gitignore exclusion. A public repository that is
    # already tracking substrate content is refused rather than left in that
    # state.
    refusal = _teach_substrate_rule(root, state)
    if refusal is not None:
        print("\n" + refusal["substrate_reason"])
        return refusal

    # Ask whether an org planning repository exists, rather than assuming the
    # substrate is durable where it stands. The answer is recorded so dispatch
    # knows where planner-owned content lives.
    planning_repo_exists = _ask_yes_no(
        "Does a private per-org planning repository exist for this project? (y/n): "
    )
    state["planning_repo_exists"] = planning_repo_exists

    _save_state(root, state)

    return state


def load_onboarding_state(project_root: str = ".") -> Optional[dict]:
    path = os.path.join(os.path.abspath(project_root), ONBOARDING_STATE_PATH)
    if not os.path.exists(path):
        return None
    try:
        with open(path) as f:
            return yaml.safe_load(f)
    except Exception:
        return None


def _save_state(project_root: str, state: dict):
    path = os.path.join(project_root, ONBOARDING_STATE_PATH)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        yaml.dump(state, f, default_flow_style=False)


def _ask_phase() -> str:
    phases = ["discovery", "blueprint", "design", "build", "release", "launch", "post-release"]
    print("\nSelect your current phase:")
    for i, p in enumerate(phases, 1):
        print(f"  {i}. {p}")
    while True:
        try:
            choice = int(input(f"Enter number (1-{len(phases)}): "))
            if 1 <= choice <= len(phases):
                return phases[choice - 1]
        except ValueError:
            pass
        print("Invalid choice. Try again.")
